---
title: What Nearby and Deferred Quotes Tell Us about Linkages and Adjustments to Information
author:
  - name: Mindy L. Mallory
    email: mallorym@illinois.edu
    affiliation: University of Illinois
    footnote: Corresponding Author
  - name: Philip Garcia
    email: p-garcia@illinois.edu
    affiliation: University of Illinois
  - name: Teresa Serra
    email: tserra@illinois.edu
    affiliation: University of Illinois
address:
  - code: University of Illinois
    address: Agricultural and Consumer Economics, 1301 W Gregory Dr, Urbana, IL, 61801
abstract: |
  The recent 'Financialization' of commodity futures markets, increases in biofuel production, and climate change potentially have   imposed profound shifts in the way commodity futures markets operate. This article examines the corn market quote-by-quote to     develop metrics on liquidity and transmission of information. The metrics are based on insights derived from sequential trading   models on single securities, index futures on a basket of securities, and special features of commodity futures markets.          Correlation between quote revisions in nearby and deferred contracts measure information-based activity, and correlations         between revisions of the time lagged nearby and deferred maturity measure the speed at which information is transmitted among     the different futures maturities. Information-based trading results in near perfect correlation between revisions to bids and     offers in nearby and deferred contracts. Within one second, information is fully transmitted from nearby to deferred contracts.

keywords: market, microstructure
bibliography: bbobas.bib
output: rticles::elsevier_article

---




# Introduction
There has been recent concern about whether and how the 'Financialization of Commodity Markets' has impacted market efficiency and efficacy in the traditional roles of risk mitigation, coordinating production, and coordinating consumption through time [@Irwin01032011; @NBERw19642; @Irwin2012256; @Henderson01052015]. Further, the recent increase in the production of biofuel from food commodities and volatile crude oil prices has changed the relationship between food and energy commodities [@Serra2013141;@Mallory20122157; @Gardebroek2013119;  @Vacha2013233; @Avalos2014253; @trujillo2012volatility]. Additionally, climate change, rising demand for agricultural commodities, and volatile inventories and exchange rates have imposed structural changes in commodity markets [@balcombe2011nature; @gilbert2010food; @prakash2011rising].  
  
These issues represent potentially profound shifts in the way commodity markets operate, and the articles cited above have considered their implications. However, how these changes affect commodity markets tick-by-tick and quote-by-quote needs to be considered. Since global price discovery occurs on global futures exchanges for the major food commodities, a deep consideration of these changes on trading activity, patterns, and consequences is warranted. We use "high frequency data" (time stamped to the second), in order to capture faster price change adjustments taking place after significant technical developments in trading platforms in the second half of the 2000s, characterized by high speed trading.

Price analysis can be classified into structural and non-structural studies. While structural models rely on economic theory, non-structural analyses identify empirical regularities in the data. The approach throughout this article is non-structural. We employ this approach primarily because there is scant market microstructure literature developed with the particular characteristics of commodity futures markets in mind. In this article, we are motivated to develop initial metrics of information-based activity in commodity markets. We anticipate this work will lead to future developments in the microstructure of commodity markets literature.

Even how to develop simple metrics of information-based activity from standard microstructure models is not obvious because standard models of trading securities are not necessarily directly applicable to commodity futures markets. For example, in commodities futures markets several contracts with different maturities trade in the marketplace, each reacting to information- and liquidity-motivated trades. Each contract responds to information-based shocks because there is a cost to store the physical commodity through time [@working1948theory; @working1949theory; @brennan1958supply]. Further, each contract maturity attracts different levels of liquidity, and it is not known what impact a lack of liquidity has on information transmission up the forward curve. 

The metrics we develop in this article on liquidity and transmission of information are based on insights we combined from the sequential trading models on single securities, index futures based on a basket of securities, and some of the features of commodity futures markets described in the preceding paragraph. Using the standard sequential trading result that quote revisions only occur if liquidity providers have updated their beliefs about the value of the security after observing order flows, the correlation between quote revisions in nearby and deferred contracts can be used to measure information-based activity, and correlations between revisions of the time lagged nearby and deferred maturity can be used to measure the speed at which information is transmitted among the different futures maturities. This metric is sensible in commodity futures markets but not in a market for a single security, because futures markets have multiple maturity contracts that should respond to information in a very similar and predictable way. We find information is fully transmitted along the forward curve so that nearby and distant contracts have fully adjusted to new information within one second. 

The remainder of the article is organized as follows. First, we provide a background of the sequential trading and index futures microstructure literature and describe the conceptual framework that motivates our interpretation of correlations of quote revisions as a metric of information-based activity. Next we describe the data and report the results of our analysis. Finally, we offer concluding remarks.


# Literature Review
The literature on how information affects liquidity in securities markets is long and rich.^[The interested reader can refer to @o1995market for an excellent and detailed overview of the evolution of this literature.] @bagehot1971only is regarded as the first to demonstrate that a bid-ask spread (BAS) arises when asymmetric information is present even if inventory and transactions costs are assumed to be zero. @copeland1983information buid upon Bagehot's work by assuming that a specific proportion of traders are informed. Knowing this, the market maker adjusts his quoted bids and offers to maximize expected profit. Copeland and Galai's model, however, does not account for the fact that the trades themselves can reveal information about whether or not traders are informed. @glosten1985bid formalize this concept and develop a model where the market maker adjusts his beliefs based on the trades that occur. The market maker knows that at least some of the traders are informed so sell orders revise the market maker's belief downward about the value of the security and buy orders revise his belief upward. They show that the spread is increasing in the proportion of informed traders, and there is a point at which too many informed traders require the market maker to set the spread so wide, that trade does not occur and the market halts (an example of the famous "Market for Lemons" described by @akerlof1970market).

@easley1987price and @easley1992time incorporate trade size and its effect to a model similar to Glosten and Milgrom. A market maker must set breakeven bid and offer quotes knowing that he faces a certain proportion of informed traders who only trade if they receive a signal that an information event has occurred, and a certain proportion of uninformed traders who do not receive an information signal but occasionally need to trade for liquidity reasons. Both informed and uninformed traders can choose between a large and small block trading size. This model setup leads to two types of equilibria: a separating equilibrium where informed traders only trade in large quantities and a pooling equilibria where informed traders may trade both large and small quantities.  This model setup of information uncertainty and asymmetric information leads to the market maker updating his beliefs about the value of the security (and therefore his quotes) based on the order flow he observes in the market. For example, in a separating equilibrium a large trading block causes the market maker to revise upward his expectation that an information event has occurred (since informed traders do not transact at small sizes). This contrasts with the pooling equilibrium where informed traders place small orders to prevent the market maker from updating his beliefs that an information event has occurred. 

@hasbrouck2006empirical provides an overview of how @easley2002information and @easley1997one use the Easley and O'Hara models of informed trading to develop a measure of the probability of informed trading (PIN). This measure, though, is estimated solely based on the sequence of order arrivals, where a trade is labeled as buyer initiated if the trade occurs above the midpoint of the quoted spread and seller initiated if the trade occurs below the midpoint of the quoted spread. Numerous studies have documented that there may be problems with downward bias in the estimated PIN [@Yan2012454; @Vega2006103; @Boehmer200726] and estimating information-based trading in this way ignores some aspects of futures markets discussed above that are not present in securities markets. For these reasons we seek an alternative to the PIN measure of information-based trading in commodity futures.

To our knowledge, there are no market microstructure models that explicitly take into account the features of commodity futures markets. The closest models come from work on index futures that cover a basket of securities. Most prominent is the work by @kumar1994information who assume *N* different non-dividend paying securities and an index futures contract on a buy-and-hold portfolio of a subset of these stocks. In Kumar and Seppi's model, specialists in the cash market observe a signal, and floor traders of the futures index observe a signal about the value of the index but not the individual securities. A key feature they build into the model is a lag in the information transmittal between the cash and futures markets because specialists only observe order flows from their own market, and not the other. This lag in information transmittal allows for arbitrageurs, who possess faster telecommunication technologies, to learn from transactions in both markets and make profitable trades in the cash and futures markets. These arbitrageurs are analogous to spread traders who trade in both nearby and deferred contracts hoping to profit on relative price movements.

There are some important distinctions between the arbitrageurs as proposed in the Kumar and Seppi model and spread traders in a futures market. Namely, the basis between a composite of cash security prices and the price of a futures index of the same basket should behave in very predictable ways (the basis, in theory, should only vary with interest rates and expected changes in dividend yields if information is symmetric). In contrast, the spread between the prices of two commodity futures contracts with different maturities depends on many more uncertain structural variables: e.g., domestic and international consumption, exchange rates, production or distribution bottlenecks, or weather. The arbitrageurs in Kumar and Seppi's model need only to wait for others in the marketplace to learn to profit. The futures market spread trader entertains much more risk in betting on relative price changes between two futures maturities.  

In the next section we draw insights from the sequential trading models described above to generate empirical predictions about the correlations between revisions to bids and offers of nearby and deferred maturity commodity futures contracts.

# Conceptual Framework
In this section we develop a conceptual framework for how the role of liquidity-based activity versus information-based activity should affect quote revisions in a commodity futures market. Using insights from the Easley and O'Hara models, along with features of commodity futures markets, we generate empirical predictions about the correlations between revisions to quotes in the nearby and deferred maturity commodity futures contracts.  

First, consider an absence of information. In the Easley and O'Hara sequential trader models, the market maker revises his quotes only when he updates his belief that the value of the security has changed. Therefore, we interpret no changes in revisions to bids (offers) as indicative of no information having arrived to the market. Any transactions that occur at these prices, the market maker believes are conducted by uninformed traders demanding liquidity.

Conversely, when we observe revisions to the bid or offer, we can infer that the market maker from the Easley and O'Hara models has updated beliefs about information arrival to the market based on past order flows. These revisions to the bid and offer we interpret as indicative of information arriving to the market.

Now we discuss features of futures markets that we can utilize when considering revisions to nearby and deferred contract quotes. First, in actively traded commodity futures markets there is no market maker, but there are entities who actively supply liquidity to the market under a variety of motives. Since the Easley and O'Hara models consider a competitive market maker, it is irrelevant whether there is one market maker in the traditional sense or a large number of traders providing liquidity. Second, when market makers revise their beliefs that an information event has arrived to the market, they know it affects futures contracts of all maturities so quotes must be revised in all contracts.

This should induce a high degree of correlation between bid and offer revisions when an information event arrives. Further, one market maker would revise bids and offers on futures contracts of all maturities at the same time they update beliefs about an information event having occurred. As a practical matter, many independent traders provide liquidity to the market at any given time, so it is not clear that the Bayesian updating described in the Easley and O'Hara models will happen in all maturities simultaneously. Therefore, it is of interest to consider the relationship between revisions to quotes in the nearby contract at different time lags) and revisions to quotes in deferred maturity contracts.

# Data
The data used in this analysis come from the CME Group's Top of Book (BBO) database for Globex corn futures quotes and transactions from 01/14/2008-11/4/2011. The data contain the best bid, bid size, best offer, offer size, last trade price, and last trade size of the order book for each active futures contract, time-stamped to the second.  

Table 1 shows the first ten entries to our data after manipulating the raw BBO data set from CME Group to display the entire top of the book on one line with the appropriate time stamp. The first column is the time-stamp, the second column is the trade sequence number, which the CME Group gives to individual trades to identify separate orders that arrive on the same second. The third column, SYMBOL, identifies which futures maturity the observation represents. In this case, 1003 stands for March 2010, with the first two characters representing the year and the second two characters representing the month. The fourth column, OFRSIZ, is the number of contracts quoted at the best offer price. The fifth column, OFR, is the best offered price. The sixth column, BIDSIZ, is the number of contracts quoted at the best bid price; the last column, BID, is the best bid price. For each date in our sample, we consider the first to mature (nearby), one, two, and three contracts deferred. We defined the nearby contract to be the next contract to expire unless the date was after the 20th of the month prior to expiration. Then we rolled the nearby to the next to expire contract. We rolled the series on the 20th to avoid decreasing volume as the contract neared the delivery period. We also excluded the September futures contract from our analysis because of low trading volume.[^sep]

Figure 1 displays average transaction price per day, number of revisions to the ask, number of revisions to the bid, and number of transactions --- all in the nearby contract. The first panel demonstrates that the time period examined was characterized by volatility, uncertainty, and rapid increases in prices in the beginning and end of the sample. Note that prices increased to a peak of nearly $8.00 per bushel in 2008, a time a time that saw a broad class of commodity markets exhibiting similar rapid price increases. Then a relatively stable period from 2009 and 2010 saw prices within a relatively tight range of $3.00 to $4.50 per bushel. In the final year of the sample, uncertainty and rapid price increases reigned again as worries about a smaller than anticipated crop yield and small ending stocks drove prices to nearly $8.00 per bushel. The number of transactions per day, depicted in the bottom panel, appears to stay within a fairly stable band throughout the sample period -- with perhaps an uptrend during the price spike of 2008 and a slight upward trend toward the end of the sample.

[^sep]: September experiences low trading volumes because deliveries on this contract sometimes (but not usually) can come from early new crop harvest, making its price relative to the traditional new crop contract, December, hard to predict. 

The second and third panel display the number of revisions to the best ask and best bid, respectively. The number of quote revisions is fairly stable within a band of about 25,000 to 50,000 revisions from 2008 to mid 2010. The exception being a brief period in late 2008 when the market had bottomed after a dramatic fall from a high that summer of nearly $8.00 per bushel. Starting in the latter period of 2010, a notable increase in the number of quote revisions, and the volatility of the number of quote revisions can be observed. While they do not stay within a well defined band, most days the number of quote revisions fall within an range of 30,000 to 75,000. Because this does not appear to coincide with a commensurate increase in the number of transactions (depicted in the bottom panel of figure 1), one must assume this is due to an increase in quoting strategies particularly suited to electronic markets. A noticeable decrease in the number of transactions, and especially the number of quote revisions is visible during the final weeks of 2008, 2009, and 2010, corresponding with the Christmas and New Year's holiday.   

While price levels were volatile, the share of contracts traded on the CME's electronic trading platform, Globex, had already stabilized to nearly 90% by 2008 [@peterson2015]. So any effects we study should not be related to trading infrastructure changes that may have occurred during the migration of volume to the electronic exchange. The data are time-stamped to the second, but trades and updates to the top of the book routinely occur more rapidly than once per second. This results in several updates to the top of the book displaying the same time stamp. This requires us to either aggregate to the second, or to simulate sub-second time stamps [@hasbrouck2015;@WangPhd14]. Since we calculate correlations between updates to the top-of-the book for several contract maturities, simulation would need to preserve (at least) the order in which updates arrived to each respective contract.  Since preserving the order of arrival across different contracts is impossible, we aggregate to the second.[^aggregate]

[^aggregate]: We take the last entry on each time-stamp for the aggregation.

Further, we exclude days on which there was a limit price move in any of the contracts, since when prices are locked at the limit, correlations are not meaningful (dates deleted due to limit price moves and the corresponding information events, if known, are as follows: 1/12/2010, revision to a Crop Production report; 3/31/2011, Prospective Plantings report; 6/30/2011, Planted Acres report; 10/8/2010, World Agricultural Supply and Demand Estimates (WASDE); and 12/9/2010, WASDE). Also, we exclude 4/5/2010, because there was an unusually high number of revisions to the best bid and best offer. Since we were not able to process all of the data for this day in a reasonable amount of computing time, we drop this day from our sample. Additionally, 7/5/2011 was an unusually light trading day after the Fourth of July holiday and resulted in no data for the third to mature contract, so we dropped this day as well.


# Analysis
Our analysis considers the correlation of logged changes to quotes in the nearby contract to logged changes to quotes in the deferred (1, 2, and 3 maturities). We described, in the Conceptual Framework section, that when information arrives to the market, it should affect the entire forward curve in the same direction. In other words, information that raises the best bid (offer) in the nearby contract, should raise the best bid (offer) in the deferred contracts as well. Linkages between the nearby and deferred contracts can be measured with simple correlations in the absence of a formal model. One of the key methodological issues when it comes to assessing high frequency data is the non-normality of price data that complicates proper modeling and requires the use of appropriate methodologies for analysis [@ait2005often; @andersen2001distribution; @easley2012volume; @hasbrouck2013high; @lee2008jumps; @lehecka2014gone].

We have two primary objectives: 1) calculate the strength of correlations between the order books of the nearby and deferred contracts, and 2) measure (or bound) the time it takes for information to be transmitted from nearby to deferred contracts. To measure the first, we calculate contemporaneous (zero time lag) correlations between the log changes of quotes in the nearby and the deferred contracts. Then, to measure the second, we calculate the correlation between time lagged log changes of quotes of the nearby with log changes of quotes of the deferred contracts. We lag the nearby by one second and ten seconds. The time lagged correlations provide a measure of how long it takes for information to be transmitted from nearby to the deferred contracts. The logic is that if we observe contemporaneous correlation between the nearby and deferred contracts, we can search for the time lag at which we observe the correlation disappearing. We conclude that information has been fully transmitted when the time lagged nearby and deferred contract order book revisions become uncorrelated. Conversely, we may observe that there is no contemporaneous correlation, but there is lagged correlation.

Since the corn futures contract experiences non-uniform trading volume throughout the day, there may be time of day effects in the strength and rate at which information is transmitted through the futures market. To capture how the speed of information transmission changes throughout the trading day, we divide the day into ten minute intervals starting at 9:30am Central Standard Time, the beginning of the daytime trading session for CBOT corn futures. We calculate the correlations described in detail below for each ten minute interval. Ten minutes was shown to be long enough for market adjustment to take place in Lehecka [-@lehecka2014gone]. This allows us to detect if there are any discernible patterns to the transmission of information over the trading day. Since one correlation is calculated per day per ten minute interval, for every ten minute interval we recover a distribution of correlations.   

## Information-Based Trading Activity and Contemporaneous Correlations in the Top of the Book


As mentioned, it is common to have multiple revisions to the order book on the same second (and consequently receive the same time-stamp in the data). The converse is also true, however. It is also common for a number of seconds to transpire before the top of the order book is revised - particularly in the middle of the daytime trading session. This results in our variables containing many zeros. How these zeros are distributed between the contracts is related to the concepts of liquidity-based versus information-based activity discussed in the conceptual framework.

To fix ideas, consider the possible outcomes when examining contemporaneous log changes in the top of the book between the nearby and the deferred contracts. There are three possibilities; on any time stamp one of the three situations may occur: 1) neither the nearby nor the deferred has a zero log change in the bid (offer), 2) either the nearby or the deferred has a zero log change in the bid (offer), but not both, or 3) both the nearby and the deferred have a zero log change in the bid (offer).

Based on the definition of liquidity-based activity and information-based activity in the conceptual framework, we present a case for interpreting (1) as information-based activity, (2) liquidity-based activity, and (3) liquidity-based activity.^[In the third case, no activity at all is observed in the quoted price changes, but quoted quantities may have changed due to new limit orders arriving, limit orders being cancelled, or market orders arriving taking some of the quoted quantities off the book. This is indicative of liquidity-based activity as well.]

The intuition is that if both the nearby and deferred contracts experience a revision in the same direction, they are likely responding to the arrival of information to the marketplace, and best bids (offers) adjust accordingly. This is in contrast to the case where one of the two contracts experiences a revision to the bid (offer) and the other contract has no change. If one contract experiences a revision in the best bid (offer) and the other does not, it is likely that the revision results from a liquidity-based order in traders’ efforts to exit their positions.  

If this intuition is correct, it is informative to consider only time-stamps for which both contracts experienced a revision - that is isolating what we are referring to as information-based activity to case (1) above. 

\begin{equation} \label{corBB} 
corr^{Bid}_{tI} = \frac{\sum\limits_{i=1}^{n} \left(bid_{ti}^N - \overline{bid_t^N}\right) \left(bid_{ti}^D - \overline{bid_t^D}\right)}{\sqrt{\sum\limits_{i=1}^{n} \left(bid_{ti}^N - \overline{bid_t^N}\right)^2 \sum\limits_{i=1}^{n}\left(bid_{ti}^D - \overline{bid_t^D}\right)^2}} \: \textrm{such that} \: bid_{ti}^N \: \textrm{and} \: bid_{ti}^D \neq 0
\end{equation} 

Equation \ref{corBB} indicates that we calculate the correlation between the log change of the nearby best bids, $bid_{ti}^N$, and the log change of the deferred best bids, $bid_{ti}^D$, for every day, *t*, and in every 10-minute interval in the daytime trading session, *I*, using the observations, *i*, when both the nearby and the deferred best bid log chnges are not equal to zero ($bid_{ti}^N \: \textrm{and} \: bid_{ti}^D \neq 0$). The correlations from equation (1) are calculated for the nearby and one deferred, nearby and two deferred, and nearby and three deferred contracts. 

Similarly equation \ref{corOO} indicates that we calculate the correlation between the log change of the nearby best offer, $offer_{ti}^N$, and the log change of the deferred best offer, $offer_{ti}^D$ for every day, *t*, and in every 10-minute interval in the daytime trading session, *I*, using the observations, *i*, when both the nearby and the deferred best offer are not equal to zero,  ${offer_{ti}^N \: \textrm{and} \: offer_{ti}^D} \neq 0$. 

\begin{equation} \label{corOO}
\begin{split}
& corr^{Offer}_{tI} = \frac{\sum\limits_{i=1}^{n} \left(offer_{ti}^N - \overline{offer_t^N}\right) \left(offer_{ti}^D - \overline{offer_t^D}\right)}{\sqrt{\sum\limits_{i=1}^{n} \left(offer_{ti}^N - \overline{offer_t^N}\right)^2 \sum\limits_{i=1}^{n}\left(offer_{ti}^D - \overline{offer_t^D}\right)^2}} \\
& \textrm{such that} \: {offer_{ti}^N \: \textrm{and} \: offer_{ti}^D} \neq 0 
\end{split}
\end{equation}

The correlations from equations \ref{corBB} and \ref{corOO} are calculated for the nearby and one deferred, nearby and two deferred, and nearby and three deferred contracts.

## Speed of Information Transmission and Time-Lagged Correlations in the Top of the Book

To provide insights on the speed at which information is transmitted from the nearby to the deferred contracts, we lag the nearby series of log changes in the bid (offer) and calculate the correlation with the deferred bids (offers). This allows us to determine the length of time it takes for information to be fully transmitted to the deferred contracts. The assumption is that the length of time it takes for the revisions to the top of the nearby limit order book to become uncorrelated with revisions to the top of the deferred limit order books is the length of time it takes for information to be transmitted between the two markets.

\begin{equation} \label{corLBB}
corr^{LagBid}_{tI} = \frac{\sum\limits_{i=2}^{n} \left(bid_{t(i-1)}^N - \overline{bid_t^N}\right) \left(bid_{ti}^D - \overline{bid_t^D}\right)}{\sqrt{\sum\limits_{i=1}^{n} \left(bid_{t(i-1)}^N - \overline{bid_t^N}\right)^2 \sum\limits_{i=1}^{n}\left(bid_{ti}^D - \overline{bid_t^D}\right)^2}} \: \textrm{such that} \: {bid_{t(i-1)}^N \: \textrm{and} \: bid_{ti}^D} \neq 0
\end{equation}

Equation \ref{corLBB} indicates that we calculate the correlation between the lagged log change of the nearby best bid, $bid_{t(i-1)}^N$, and the log change of the deferred best bid, $bid_{ti}^D$ for every day, *t*, and in every 10-minute interval in the daytime trading session, *I*, using the observations, *i*, when both the lagged nearby and the deferred best bid are not equal to zero,  ${bid_{t(i-1)}^N \: \textrm{and} \: bid_{ti}^D} \neq 0$. 

\begin{equation} \label{corLOO}
\begin{split}
& corr^{LagOffer}_{tI}  = \frac{\sum\limits_{i=1}^{n} \left(offer_{t(i-1)}^N - \overline{offer_t^N}\right) \left(offer_{ti}^D - \overline{offer_t^D}\right)}{\sqrt{\sum\limits_{i=1}^{n} \left(offer_{t(i-1)}^N - \overline{offer_t^N}\right)^2 \sum\limits_{i=1}^{n}\left(offer_{ti}^D - \overline{offer_t^D}\right)^2}} \\
& \textrm{such that} \: {offer_{t(i-1)}^N \: \textrm{and} \: offer_{ti}^D} \neq 0
\end{split}
\end{equation}

Similarly, equation \ref{corLOO} indicates that we calculate the correlation between the lagged log change of the nearby best offer, $offer_{t(i-1)}^N$, and the log change of the deferred best offer, $offer_{ti}^D$ for every day, *t*, and in every 10-minute interval in the daytime trading session, *I*, using the observations, *i*, when both the lagged nearby and the deferred best offer are not equal to zero,  ${offer_{t(i-1)}^N \: \textrm{and} \: offer_{ti}^D} \neq 0$. 

## Spread Trades, Information Transmission, and Time-Lagged Bid-to-Offer (Offer-to-Bid) Correlations  

Surely the spread trade is an important component that keeps nearby and deferred contracts linked in economically meaningful ways. However, a spread trade is entered as a buy (sell) in the nearby and an sell (buy) in the deferred contract. Until now, we have presented correlations between bib-to-bid and offer-to-offer in the nearby and deferred contracts. In equation \ref{corrLBO}, we define a measure of how correlations between lagged log changes in the nearby bid and log changes in the deferred offer measure the effect of spread traders in transmitting information up the forward curve.

\begin{equation} \label{corrLBO}
corr^{LagBO}_{tI} = \frac{\sum\limits_{i=1}^{n} \left(bid_{t(i-1)}^N - \overline{bid_t^N}\right) \left(offer_{ti}^D - \overline{offer_t^D}\right)}{\sqrt{\sum\limits_{i=1}^{n} \left(bid_{t(i-1)}^N - \overline{bid_t^N}\right)^2 \sum\limits_{i=1}^{n}\left(offer_{ti}^D - \overline{offer_t^D}\right)^2}} \: \textrm{such that} \: {bid_{t(i-1)}^N \: \textrm{and} \: offer_{ti}^D} \neq 0
\end{equation}

Where we calculate the correlation between the lagged log change of the nearby best bid, $bid_{t(i-1)}^N$, and the log change of the deferred best offer, $offer_{ti}^D$, for every day, *t*, and in every 10-minute interval in the daytime trading session, *I*, using the observations, *i*, when both the lagged nearby and the deferred best offer are not equal to zero, when both the lagged nearby offer and the deferred best bid are not equal to zero,  ${bid_{t(i-1)}^N \: \textrm{and} \: offer_{ti}^D} \neq 0$.

\begin{equation} \label{corrLOB}
corr^{LagOB}_{tI} = \frac{\sum\limits_{i=1}^{n} \left(offer_{t(i-1)}^N - \overline{offer_t^N}\right) \left(bid_{ti}^D - \overline{bid_t^D}\right)}{\sqrt{\sum\limits_{i=1}^{n} \left(offer_{t(i-1)}^N - \overline{offer_t^N}\right)^2 \sum\limits_{i=1}^{n}\left(bid_{ti}^D - \overline{bid_t^D}\right)^2}} \: \textrm{such that} \: {offer_{t(i-1)}^N \: \textrm{and} \: bid_{ti}^D} \neq 0
\end{equation}

Similarly for equation \ref{corrLOB} we calculate the same correlations as in equation \ref{corrLBO} except that we use the lagged nearby offer and the deferred bid. 

## USDA Announcement Days
On USDA report announcement days there is often a significant amount of information that market participants receive at the same time, causing large price fluctuations and larger than usual trading volumes. Therefore, in our analysis we also separate out days on which major USDA reports are released and calculate the same correlations described above. During our sample period, the USDA reports we include were released at 8:30 am CST, before the day trading session began.

# Results

Table 2 contains a synopsis of the results that will be presented as figures 2, 3, and 4. Figure 2 presents the strength of the correlation between the nearby and deferred contracts by calculating the contemporaneous correlation between log changes of nearby bids (offers) and log changes of deferred bids (offers). Figure 3 presents the strength of the correlation of log changes of nearby bids (offers) and log changes of first deferred bids (offers) at time lags of 0, 1, and 10 seconds. Figure 4 presents the strength of the correlation of log changes of nearby bids (offers) and log changes of first deferred offers (bids) at time lags of 0, 1, and 10 seconds. Each figure is organized in a similar way. The top pane shows correlations with the nearby bid, next shows correlations with the nearby offer, next shows correlations with the nearby bid on USDA report days, and finally the last pane shows correlations with the nearby offer on report days. The dots represent the mean of the distribution of calculated correlations and the bars represent one standard deviation of the distribution of calculated correlations.  


## Information-Based Trading Activity and Contemporaneous Correlations in the Top of the Book
In figure 2 contemporaneous correlation between the nearby and one, two, and three deferred maturity contracts are displayed. Calculations are made based on time-stamps where both the nearby and deferred maturity experience non-zero revisions to the best bid (top panel) or offer (second panel). The contemporaneous correlations between each nearby and deferred contract pairs are very close to one for both best bids (top panel) and best offers (second panel). The exception being that there is a slight dip in correlations at the first and last ten minutes of the trading day.

This implies that in the event both contracts experience revisions to their respective limit order books, they are revised in lockstep. While some of this correlation is artificially induced due to the tick structure of price changes in this market (prices move in a minimum of 0.25 cent increments.), the correlations are too strong to attribute it all to that. Additionally, since our data is only time-stamped to the second, we may miss nuance that would be captured with data time stamped to the millisecond. Regardless, the result is surprisingly strong and indicates that information is largely transmitted up the forward curve in less than one second. It is interesting that the distribution of correlations between the nearby and 1, 2, and 3 deferred contract bids are at such similar levels, hovering very close to one. Transmission of information to the third deferred contract seems to be as strong as transmission to the first deferred contract. 

The bottom two panels of figure 2 are exactly analogous to the top two except that they focus on USDA report days. We see a remarkably similar depiction compared in that the correlations hover near one throughout the trading day. If there had been a difference in the pattern of correlations on USDA report days, one would expect the first ten minutes of trading to display the largest effect. There is visibly more variation in the means of these distributions, presumably as much a result of the much smaller sample of report days versus non-report days.  

We suspect two primary reasons that the full sample and USDA report day results are so similar: 1) Since we removed days where the report release corresponded to limit price moves, we systematically removed report days where the most important information was conferred on the market. It is possible that the remaining days corresponded to USDA reports that were more easily translated to market impacts by traders, and thus created results in figure 2 that look similar to a normal trading day, while we systematically excluded report days containing larger information shocks and presumably are harder for traders to interpret the market impact of the report. 2) Since USDA reports were released prior to the market open during this time period, the information may have already been fully incorporated by market participants by the time the market opened, resulting in no discernible difference in the pattern of correlations in the first (and subsequent) time bins. 

  
## Speed of Information Transmission and Time-Lagged Correlations in the Top of the Book

Figure 3 contains the correlations between log changes of the nearby and log changes of one deferred contracts at 0, 1, and 10 second time lags, when both experience non-zero changes. The graph shows the contemporaneous correlation from figure 2 as a reference, and correlations generated by lagging the nearby by one second and ten seconds respectively. Here we expected to see a clear pattern of decreased correlation as we increased the length of the time lag in the nearby - reflecting that information is transmitted from nearby to deferred contracts over a number of seconds. However, we see that the correlation drops to zero with a lag of one second, which in this data set is the shortest time lag possible. 

There are three possible explanations for this. First, it is possible that there is in fact a clear and decreasing correlation between lags of the nearby and the deferreds, but it can only be observed on mili- or micro-second time stamps. Then, when aggregating to the nearest second, we observe contemporaneous correlation close to one, but zero correlation even at the shortest possible time lag (one second). 

Second, we explicitly assumed that price discovery happens in the nearby contract when we lagged the nearby contract instead of the deferred contract. If price discovery happens in the deferred contract, and takes time to fully to be incorporated into the nearby contract, then we would observe non-zero correlation between nearby quote revisions and lagged *deferred* quote revisions. When we did this, we observed a very similar result as is presented in figure 3 - zero correlation at 1 and 10 second time lags of the deferred contract; this means there is not evidence to support that price discovery happens in the deferred contracts.[^not] Information seems to be fully transmitted within one second to the first deferred contract.    

[^not]: This figure is not presented in the interest of brevity. 

Third, zero correlations between the deferred and time lagged nearby would also occur if linkages between the nearby and deferred contracts were immediately enforced by spread traders. This is examined in figure 4. 

## Spread Trades, Information Transmission, and Time-Lagged Bid-to-Offer (Offer-to-Bid) Correlations

Figure 4 displays the means and error bars of the correlations between log changes of the lagged nearby bid (offer) revisions and log changes of the first deferred offer (bid) revisions. Here, as in figure 3 we see contemporaneous correlations hovering near one. We observe that while the correlations when the nearby is lagged by both one second and ten seconds are near zero, the mean of the one second lagged correlations are clearly higher than the ten second lags and larger than zero. It is not compelling evidence, however, that we have observed incomplete information transmission at the one second horizon. Though positive, it is still quite close to zero. 



# Conclusions


Recent developments in commodity markets make it important to assess price adjustment patterns with high frequency data. We focused this paper on the corn market because it has experienced some of the most pronounced changes in recent years. We gleaned insights from the sequential trading market microstructure literature to generate metrics of informed versus liquidity trading in commodity futures markets. Sequential trading models allow liquidity providers to learn about the existence of information arrivals and their directional implications for security prices.  From these models we infer that market makers detect no new market information if we observe no changes to the best bid or best offer in the limit order book. This is because in sequential trading models, the market maker learns about the probability of an information event from trader order flows and revises his breakeven bids and offers accordingly.

We use simple correlations between non-zero log changes to the best bid (offer) in the limit order book as our metric of information-based activity in the market. Our results for CBOT corn indicate that the mean contemporaneous correlation between non-zero changes to the nearby and all deferred contracts was very close to 1 throughout the trading day. When information arrives to the market, liquidity providers in contracts of all maturities revise their bids and offers in lockstep (or in less than one second) to reflect the new information.

To measure the speed of information transfer from nearby to deferred maturities, we lagged the nearby by one and ten second respectively and computed correlations in revisions to the best bid (offer) with deferred contracts. We find that even at a one second lag, the shortest time lag possible with this data set, the correlation between revisions to the best bid and best offer dropped to zero. 

These results indicate that we can learn much from trades and quotes data about how many informed traders there are in a marketplace, but it is clear that much additional work in this area is needed. We borrowed from the sequential trading in securities literature, but future research is needed to develop sequential trading models specific to commodity futures markets. Such a model would provide richer insights into trading and behavior of markets.




# References


